function prettyPrintMetrics(name, M)
    fprintf(['%-8s | Lp=%9.2f m | kappa_avg=%6.2f deg | kappa_max=%6.2f deg | ', ...
             'climb_avg=%6.2f m | climb_max=%6.2f m | Cmin=%7.2f m | Vr=%6.2f %% | Collision=%6.2f %%\n'], ...
        name, M.Lp, M.kappa_avg, M.kappa_max, ...
        M.climb_avg, M.climb_max, M.Cmin, M.Vr, M.Collision);
end
